# Generated by Django 3.0.8 on 2020-08-01 09:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(blank=True, db_index=True, null=True)),
                ('from_number', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('to_number', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('duration', models.IntegerField(blank=True, db_index=True, null=True)),
                ('call_type', models.CharField(blank=True, db_index=True, default='outgoing call', max_length=20, null=True)),
                ('imei', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('cell_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('location_lat', models.FloatField(blank=True, db_index=True, null=True)),
                ('location_long', models.FloatField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPDR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(blank=True, db_index=True, null=True)),
                ('duration', models.IntegerField(blank=True, db_index=True, null=True)),
                ('private_ip', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('private_port', models.IntegerField(blank=True, db_index=True, null=True)),
                ('public_ip', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('public_port', models.IntegerField(blank=True, db_index=True, null=True)),
                ('destination_ip', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('destination_port', models.IntegerField(blank=True, db_index=True, null=True)),
                ('from_number', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('imei', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('imsi', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('cell_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('location_lat', models.FloatField(blank=True, db_index=True, null=True)),
                ('location_long', models.FloatField(blank=True, db_index=True, null=True)),
                ('upload_data_volume', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('download_data_volume', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('last_known_location', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imsi', models.CharField(db_index=True, max_length=20)),
                ('mobile_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.MobileNumber')),
            ],
        ),
        migrations.AddField(
            model_name='mobilenumber',
            name='associated_person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mobiles', to='data.Person'),
        ),
        migrations.AddField(
            model_name='mobilenumber',
            name='person_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_mobile', to='data.Person'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('mac', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('mobile_numbers', models.ManyToManyField(blank=True, to='data.MobileNumber')),
                ('persons', models.ManyToManyField(blank=True, db_index=True, to='data.Person')),
            ],
        ),
    ]
