# Generated by Django 3.0.8 on 2020-08-01 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilenumber',
            name='person_ptr',
        ),
        migrations.AddField(
            model_name='cdr',
            name='imsi',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mobile_numbers',
            field=models.ManyToManyField(blank=True, db_index=True, to='data.MobileNumber'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='persons',
        ),
        migrations.AddField(
            model_name='device',
            name='persons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Person'),
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='associated_person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_numbers', to='data.Person'),
        ),
    ]
