# Generated by Django 3.0.8 on 2020-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200801_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('ip', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('port', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cdr',
            name='from_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='to_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
