# Generated by Django 3.0.8 on 2020-08-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200801_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
