# Generated by Django 3.0.8 on 2020-08-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200801_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='persons',
            new_name='person',
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('cdr_record', models.ManyToManyField(blank=True, to='data.CDR')),
                ('devices', models.ManyToManyField(blank=True, to='data.Device')),
                ('ipdr_record', models.ManyToManyField(blank=True, to='data.IPDR')),
                ('mobile_numbers', models.ManyToManyField(blank=True, to='data.MobileNumber')),
                ('sim_cards', models.ManyToManyField(blank=True, to='data.SimCard')),
            ],
        ),
    ]
