# Generated by Django 3.0.8 on 2020-08-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200801_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('to_display', models.BooleanField(default=True)),
                ('raw_data', models.TextField()),
                ('persons', models.ManyToManyField(blank=True, to='data.Person')),
            ],
        ),
    ]
