# Generated by Django 3.0.8 on 2020-08-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(db_index=True, max_length=20)),
                ('value', models.CharField(db_index=True, max_length=100)),
            ],
        ),
    ]
