# Generated by Django 3.0.8 on 2020-08-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='persons',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='users_list',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
