# Generated by Django 3.0.8 on 2020-08-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200802_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anomaly',
        ),
    ]
