# Generated by Django 3.0.8 on 2020-08-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_delete_anomaly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdr',
            name='start_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
