# Generated by Django 3.0.8 on 2020-08-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20200802_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_text',
        ),
    ]
