# Generated by Django 3.0.8 on 2020-08-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alertinstance_tracked_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertinstance',
            name='cdr_instance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertinstance',
            name='ipdr_instance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
