# Generated by Django 3.0.8 on 2020-08-03 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20200803_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('alert_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.AlertInstance')),
            ],
        ),
    ]
